### ISSUE TITLE
Fatal B9PS error when using Kerbalism: Science Only config or other configs of Kerbalism?

### ISSUE THREAD

**Issue by ratemisia** [JadeOfMaar/SterlingSystems#5]
Hello! I tested version 0.4.0.1 with Kerbalism: Science Only config (and another life support mod) installed on KSP 1.12.5, and I get a fatal "No resource definition named 'Shielding' could be found" error. I'll try to get a log from a clean install other than these mods shortly. 
![Here's an image of the B9 Part Switch error in the meantime.](https://github.com/user-attachments/assets/1c775c8e-10b4-48d8-8e36-ed4c696bfce5)
From what I can see, this isn't intended behavior - it seems like Sterling's patches related to Shielding are supposed to require KerbalismDefault, but I don't have KerbalismDefault installed. I can confirm that this error _does not_ happen if I don't have Kerbalism installed at all, I only get the fatal error when testing with a Kerbalism config other than default. Hopefully I'll be able to diagnose further.

**Comment by ratemisia** [comment]
Here's a log from a clean install (only the Sterling Systems mods, Kerbalism Science Only config, B9 Part Switch, and dependencies):
[KSP.log.zip](https://github.com/user-attachments/files/16517552/KSP.log.zip)
And here's my GameData on said install:
![image](https://github.com/user-attachments/assets/499b2961-a242-40db-b35e-4f0b3881110b)
Worthwhile to mention at this point that I'm testing on Linux (Mint 21.3 x86_64). I think this would be reproduced the same way on Windows, though.

**Comment by ratemisia** [comment]
I'd be happy to provide more information if requested.

**Comment by ratemisia** [comment]
> In the meantime, I'll be sanity checking by loading with the Default Config to be sure I don't get the same error.
No errors with Kerbalism's Default Config. This is unique to other configs.

**Comment by JadeOfMaar** [comment]
> Kerbalism profiles other than Default somehow still identify as Default, which causes MM to detect "KerbalismDefault" which lets the Shielding resource patch run, but these other profiles don't supply the resource definition since it's not relevant to them. Simply deleting this is the easiest solution.
> - Comment https://github.com/JadeOfMaar/SterlingSystems/commit/a26e8f9c2da3137e491ebd93428d2187c7b317cf

@ratemisia delete GameData/SterlingSystems/Thermals/zPatches/KerbalismShielding.cfg
